INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (1, 'Lit', 499, 'meuble');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (2, 'Lampe', 69, 'éclairage');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (3, 'Bureau', 270, 'décoration');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (4, 'TV', 1299, 'électronique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (5, 'Peluche', 19, 'cosmétique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (6, 'Rouge a Levre Louie Teton', 2710, 'cosmétique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (8, 'Marteau', 9, 'bricolage');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (9, 'Scie', 23, 'bricolage');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (10, 'Cracbook', 4300, 'électronique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (11, 'iPome', 809, 'électronique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (12, 'Pineapple Watch', 459, 'électronique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (13, 'Echo bot', 49, 'électronique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (14, 'Casque Raser', 73, 'électronique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (15, 'Switsh OLED', 369, 'électronique');
INSERT INTO Produit (Nprod, nomProd, prix, categorie) VALUES (16, 'Slip', 36, 'vetements');